### PR TITLE
Script should work now ;)

### PR DESCRIPTION
**Pull request by stugol**

### CODE REVIEW

**Comment by stugol** [comment]
Lack of a `realpath` call in `/opt/onyx/bin/onyx` was causing a heisenbug if onyx was invoked with a relative path, e.g:
```
cd /opt/onyx
echo 'say' | bin/onyx eval
```
Crystal suffers from this same defect, incidentally.

**Comment by ozra** [comment]
Thanks!

**Comment by ozra** [comment]
Confirmed to work fine on my Ubuntu 15.10 too.
Only thing was it said "Compiling 32 bit onyx". But the resultant onyx-bin is 64-bit, so it's just the text that's off.

**Comment by stugol** [comment]
That's very strange. What about the other messages? Do they say 64-bit? What is the output of `uname -a` on your system?

**Comment by ozra** [comment]
Linux GhostBook64 3.16.0-45-generic #60~14.04.1-Ubuntu SMP Fri Jul 24 21:16:23 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Oddly enough reports a different version of Ubuntu than `lsb_release -a`

It was only the compile message that showed 32.

**Comment by stugol** [comment]
That's a lot of `x86_64s` you got there.

**Pull request merged**
