### PR TITLE
Javascript-style hash literal `{key: val}`

### PR DESCRIPTION
**Pull request by ozra**
The keys becomes string literals.

### CODE REVIEW

**Comment by stugol** [comment]
And if you want tag keys? Maybe `#key val` or `key#val`?

**Comment by ozra** [comment]
```onyx
my-hash = {
   key: "some val"
   other-key: "val"
} --> keys are Strings

my-hash = {
   #key: "some val"
   #other-key: "val"
} --> keys are Tags
```

**Comment by stugol** [comment]
Alright.

**Comment by ozra** [comment]
```onyx
key = #key
other-key = "other-key-aye"

my-hash = {
   key => "some val"
   other-key => "val"
} --> keys parsed as expressions

```

**Pull request merged**
